# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: M. Isabel Agea
email: agealorm@vscht.cz
description: > # this means to ignore newlines until "baseurl:"
  A Spanish girl exploring the world since 1993. 
  I completed my BS in Biotechnology in an attempt to understand 
  the molecular mechanisms of life, my M.Sc. in Bioinformatics after falling 
  in love with it, and nowadays I am a PhD student in the field of Drug Design 
  at the University of Chemistry and Technology in the amazing city of Prague. 
  Passionate about science, puzzles, travelling, sports and beer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
linkedin_username: isabelagealorente
github_username:  Iagea

# Build settings
markdown: kramdown

theme: jekyll-theme-leap-day
